### ISSUE TITLE
What’s the plan here?

### ISSUE THREAD

**Issue by erlend-sh** [PsichiX/emergent#1]
Were you planning to base this project on some specific prior art? I’m designing emergent game features as well so I’m very curious to know more about your intention here.

**Comment by PsichiX** [comment]
This crate (while it is still placeholder) will be based on my general purpouse set of algorithms for smart events triggering - nothing revolutionary. if you need some inspiration, check Walking Dead GDC talks about emergent gameplay, that may be helpful. this crate will be published in few months, as part of big game toolset :)

**Comment by PsichiX** [comment]
@erlend-sh afte two years i've finally made this crate (if you're still interested in ;p) - altho from the functionality point of view it's complete, now i'm documenting the code so next version will tell what is it and how to use it :)
