### ISSUE TITLE
machinery not send or sync

### ISSUE THREAD

**Issue by aentity** [PsichiX/emergent#2]
Hello,

Great library, and thank you for such good documentation.

I have question though: why is machinery not send or sync? It was strange to me to discover this was not so.

This causes problems if user stores the machinery as component in for example, specs. 

Thank you!

**Comment by PsichiX** [comment]
ohayo!
oh, so it's because two reasons:
- there are trait objects which are not marked as Send + Sync
- i'm stupid and i forgot to add Send + Sync to these trait objects 😮 

i'll add that in a day or two, thanks for noticing that! :D

**Comment by PsichiX** [comment]
i had to spend some time to test how that works with use in actual ECS framework, added missing Send + Sync impls is now live in version 1.5.3 :D
closing the issue
